version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Putting a bookmark on the node_modules folder (local reference)
      - .:/app # Map the pwd into the '/app' folder
  # Not a good approach because we can't send in an input to re-run
  # tests (can't easily set that up with docker-compose bc if we
  # tried to use Docker attach, it won't send the correct input
  # to the correct process that is currently running in the container)
  client-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # Overriding starting command
